version: '3'
services:
    php-fpm:
        build: ./docker/php-fpm
        image: php:7.1-fpm
        volumes:
            - ./:/var/www/html
        links:
            - mysql
    nginx:
        image: nginx:latest
        links:
            - php-fpm
        volumes:
            - ./:/var/www/html
            - ./storage/nginx-logs:/var/log/nginx
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"

    redis:
        image: redis:latest
        links:
            - php-fpm
        ports: 
            - "6379:6379"

    yarn:
        image: kkarczmarczyk/node-yarn:latest
        links: 
            - php-fpm
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        tty: true

    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=db
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        ports:
            - "3309:3306"
        volumes:
            - ./storage/mysql-data:/var/lib/mysql